CC = gcc
OUTPUT = out
SOURCE = main.c
FLAGS = -Wall -pthread -lpthread

build:
	$(CC) $(SOURCE) $(FLAGS) -o $(OUTPUT)

q1:
	$(CC) question1.c $(FLAGS) -o q1
q2:
	$(CC) question2.c $(FLAGS) -o q2
q3:
	$(CC) question3.c $(FLAGS) -o q3
clean:
	rm $(OUTPUT)
